### PR TITLE
Added automated testing for Non Rainbow Hand

### PR DESCRIPTION
**Pull request by RobertBedrosian**

### CODE REVIEW

**Comment by kyledewey** [comment]
Assigned @PatGarza20

**Comment by kyledewey** [comment]
Additionally assigned @AshotC

**Review by PatGarza20 — APPROVED** [review]
The code is clean and easy to understand, comments are much appreciated. To my understanding, this test generates a particular hand of cards and tests that that hand in particular is generated.

**Review by AshotC — APPROVED** [review]
Looks good to me, I'm happy there aren't 10x the number of spaces to code compared to what I usually see from you. I am curious why you omit one suit though.

**Pull request merged**
