### PR TITLE
Added automated testing for rainbow hands

### PR DESCRIPTION
**Pull request by RobertBedrosian**

### CODE REVIEW

**Comment by kyledewey** [comment]
Assigned @LuisAbularach

**Comment by kyledewey** [comment]
Also assigned @areeba-waheed

**Review by areeba-waheed — APPROVED** [review]
Easy to read test. LGTM!

**Review by LuisAbularach — APPROVED** [review]
Easy to understand what you're testing and how you are doing it. Looks good to me!

**Pull request merged**
