### PR TITLE
Thirdupdate

### PR DESCRIPTION
**Pull request by RobertBedrosian**

### CODE REVIEW

**Comment by kyledewey** [comment]
Assigned @areeba-waheed

**Comment by kyledewey** [comment]
Additionally assigned @cooljohnny3

**Review by cooljohnny3 — APPROVED** [review]
Tests look comprehensive for which hands are possible but are very specific to whatever hand you defined in the test.  Consider using some sort of generation of hands in order to test the rank function since that seems to be what you are testing.

**Review by areeba-waheed — APPROVED** [review]
Tests look good and readable to me. Good job!

**Pull request merged**
