### PR TITLE
No tests here, fixed a bunch of code to get the program running how i…

### PR DESCRIPTION
**Pull request by RobertBedrosian**
…t should.
I can explain the 2k line difference, there was a mistake with git and basically a bunch of my pull requests were reverted awhile back. Also a bunch of filler production/license files were recently added inflating the diff. The real diff changes are in Poker.java added lines:
599-625 fixed non rainbow checker
502-535 fixed 3 pair checker
406-461 fixed odd/even checker
~114 line diff in reality. srry :)

### CODE REVIEW

**Comment by kyledewey** [comment]
Assigned @shenhuang

**Comment by kyledewey** [comment]
Additionally assigned @shanth2600

**Review by shanth2600 — APPROVED** [review]
holy for-loop batman!

**Review by shenhuang — CHANGES_REQUESTED** [review]
Typo (out/production/OmahaPoker/Documentation):

line 16: dont -> don't
line 38: indicies -> indices

**Comment by RobertBedrosian** [comment]
updated!

**Pull request merged**
